name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      api-solid-pg:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: api-solid

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm test:e2e
        env:
          JWT_SECRET: "TESTEEEEEEEEEE"
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/api-solid?schema=public"
